### ISSUE TITLE
auto-file doesn't exist, please specify full path

### ISSUE THREAD

**Issue by oheyadam** [nowsecure/auto-circleci-plugin#7]
I keep getting this error: `auto-file doesn't exist, please specify full path /root/project/auto-circleci-plugin-1.2.1/~/project/test.apk`, but the file _does_ exist. I know because I keep ssh-ing into the job and it's always there. This is what my job setup looks like for reference:

What's going on here? Thanks

```
  now-secure:
    docker:
      - image: openjdk:8
    steps:
      - attach_workspace:
          at: ~/project
      - run: cp ~/project/app/build/outputs/apk/staging/release/app-staging-arm64-v8a-release.apk ~/project/test.apk
      - auto_ci/mobile_security_test:
          auto_file: ~/project/test.apk
          auto_token: $NOWSECURE_TOKEN
          auto_show_status_messages: "true"
```
